/**
 * Professional PDF report generator (PDFKit)
 */

const PDFDocument = require('pdfkit');

function generateBenchmarkPDF({ report, settings, result }) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks = [];
      doc.on('data', (c) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const brand = settings?.branding || {};
      const title = brand.reportTitle || 'Industry Benchmark Intelligence Report';
      const company = brand.companyName || 'Nanak Accountants';
      const footer = brand.footerText || 'Confidential – Prepared by Nanak Accountants';
      const primary = brand.primaryColor || '#f97316';

      // Cover
      doc.rect(0, 0, doc.page.width, 180).fill(primary);
      doc.fillColor('#ffffff').fontSize(11).text(company.toUpperCase(), 50, 50, { characterSpacing: 2 });
      doc.fontSize(22).font('Helvetica-Bold').text(title, 50, 80, { width: 500 });
      doc.fontSize(12).font('Helvetica').text('Confidential client advisory document', 50, 140);

      doc.fillColor('#111111').fontSize(12);
      const y0 = 210;
      doc.font('Helvetica-Bold').text('Client Details', 50, y0);
      doc.font('Helvetica').fontSize(11);
      doc.text(`Client: ${report.clientName || report.clientInformation?.name || '—'}`, 50, y0 + 22);
      doc.text(`Company: ${report.company || report.clientInformation?.company || '—'}`, 50, y0 + 38);
      doc.text(`Industry: ${report.industryName || '—'}`, 50, y0 + 54);
      doc.text(`Financial Year: ${report.financialYear || '—'}`, 50, y0 + 70);
      doc.text(`Risk Score: ${report.riskScore ?? 0} (${String(report.overallStatus || '').toUpperCase()})`, 50, y0 + 86);
      doc.text(`Benchmark Version: v${report.version || '1.0.0'}`, 50, y0 + 102);
      doc.text(`Prepared: ${new Date(report.createdAt || Date.now()).toLocaleString()}`, 50, y0 + 118);
      doc.text(`Generated By: ${report.generatedByName || '—'}`, 50, y0 + 134);

      // Comparison table
      doc.addPage();
      doc.font('Helvetica-Bold').fontSize(14).text('Benchmark Comparison', 50, 50);
      let y = 80;
      doc.fontSize(9).fillColor('#666666');
      doc.text('Ratio', 50, y);
      doc.text('Client', 200, y);
      doc.text('Min', 260, y);
      doc.text('Avg', 310, y);
      doc.text('Max', 360, y);
      doc.text('Status', 420, y);
      y += 16;
      doc.moveTo(50, y).lineTo(545, y).strokeColor('#dddddd').stroke();
      y += 8;

      const ratios = report.calculatedRatios || result?.calculatedRatios || [];
      doc.fillColor('#111111');
      for (const r of ratios.slice(0, 20)) {
        if (y > 740) {
          doc.addPage();
          y = 50;
        }
        doc.font('Helvetica').fontSize(9);
        doc.text(String(r.ratioName || r.name || '').slice(0, 28), 50, y, { width: 140 });
        doc.text(String(r.clientValue ?? ''), 200, y);
        doc.text(String(r.industryMin ?? ''), 260, y);
        doc.text(String(r.industryAverage ?? ''), 310, y);
        doc.text(String(r.industryMax ?? ''), 360, y);
        doc.text(String(r.status || ''), 420, y);
        y += 16;
      }

      // Recommendations
      doc.addPage();
      doc.font('Helvetica-Bold').fontSize(14).fillColor('#111111').text('Recommendations', 50, 50);
      y = 80;
      const recs = report.recommendations || result?.recommendations || [];
      for (const rec of recs) {
        if (y > 720) {
          doc.addPage();
          y = 50;
        }
        doc.font('Helvetica-Bold').fontSize(11).text(`[${String(rec.severity || '').toUpperCase()}] ${rec.message}`, 50, y, {
          width: 500,
        });
        y = doc.y + 4;
        doc.font('Helvetica').fontSize(10).fillColor('#444444').text(rec.recommendation || '', 50, y, { width: 500 });
        y = doc.y + 14;
        doc.fillColor('#111111');
      }

      // Signature / footer
      y = Math.max(y + 30, 650);
      doc.fontSize(10).text('Authorised Signature', 50, y);
      doc.moveTo(50, y + 40).lineTo(250, y + 40).strokeColor('#999999').stroke();
      doc.fontSize(9).fillColor('#666666').text(footer, 50, 760, { align: 'center', width: 500 });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { generateBenchmarkPDF };
